### ISSUE TITLE
Erroneous serigraphy of the button letter

### ISSUE THREAD

**Issue by bricox54** [adafruit/Adafruit-OLED-FeatherWing-PCB#9] opened 2022-07-28 07:04 UTC
Hello,
If the reference is the drawing and the board edge serigraphy then buttons A and C serigraphy are reversed.

**Comment by ladyada** [comment] 2022-07-29 14:59
this is duplicate of
https://github.com/adafruit/Adafruit-OLED-FeatherWing-PCB/issues/5

**Closed as completed by ladyada** 2022-07-29 14:59 UTC
